# Generated by Django 5.2.7 on 2025-10-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reservation_created', 'Reservation Created'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('reservation_deleted', 'Reservation Deleted'), ('room_favorited', 'Room Favorited'), ('room_unfavorited', 'Room Unfavorited')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField()),
                ('attendees', models.PositiveIntegerField(default=1)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='capacity_used',
            field=models.PositiveIntegerField(default=0, help_text='Actual attendees who showed up'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_url',
            field=models.URLField(blank=True, help_text='High-quality room image URL', null=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='api_room_is_acti_cd542a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'floor'], name='api_room_buildin_1110a3_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reservation'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringpattern',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to='api.room'),
        ),
        migrations.AddField(
            model_name='recurringpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='api.recurringpattern'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'date'], name='api_reserva_user_id_1e8597_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'date'], name='api_reserva_status_50b081_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['created_at'], name='api_reserva_created_ee6474_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reminder_sent', 'date', 'start_time'], name='api_reserva_reminde_9706b7_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_rooms',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='api.room'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='api_activit_created_011954_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='api_activit_user_id_29f0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpattern',
            index=models.Index(fields=['room', 'is_active'], name='api_recurri_room_id_c50bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpattern',
            index=models.Index(fields=['user', 'is_active'], name='api_recurri_user_id_32859b_idx'),
        ),
    ]
